create table RESERV_STATUS_DEF
(
    STATUS      VARCHAR2(10) not null
        primary key,
    STATUS_DESC VARCHAR2(50)
)
/

INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('1', '预约待审核');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('2', '预约信息初审中');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('3', '预约信息初审通过');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('4', '预约信息初审不通过');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('5', '上门实地调查中');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('6', '上门实地调查通过');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('7', '上门实地调查不通过');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('8', '待处理开户');
INSERT INTO ZG.RESERV_STATUS_DEF (STATUS, STATUS_DESC) VALUES ('9', '开户成功');