CREATE TABLE ZG.ZG_ROLE
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    NAME VARCHAR2(50),
    ROLE_LEVEL NUMBER(*),
    DESCRIPTION VARCHAR2(50)
);
INSERT INTO ZG.ZG_ROLE (ID, NAME, ROLE_LEVEL, DESCRIPTION) VALUES (1, 'admin', null, '系统管理员');