CREATE TABLE ZG.ZG_DEP
(
    DEP_CODE VARCHAR2(20) DEFAULT NULL PRIMARY KEY NOT NULL,
    DEP_DESC VARCHAR2(50) NOT NULL,
    DEP_ID NUMBER(*) DEFAULT NULL NOT NULL
);
INSERT INTO ZG.ZG_DEP (DEP_CODE, DEP_DESC, DEP_ID) VALUES ('0101', '0101-营业部', 101);
INSERT INTO ZG.ZG_DEP (DEP_CODE, DEP_DESC, DEP_ID) VALUES ('9999', '9999-清算中心', 9999);