CREATE TABLE ZG.ZG_USER
(
    ID NUMBER(*) PRIMARY KEY NOT NULL,
    CNNAME VARCHAR2(50),
    USERNAME VARCHAR2(50),
    PASSWORD VARCHAR2(50),
    EMAIL VARCHAR2(50),
    TELEPHONE VARCHAR2(50),
    MOBILE_PHONE VARCHAR2(50),
    WECHAT_ID VARCHAR2(50),
    SKILL VARCHAR2(50),
    DEPARTMENT_ID NUMBER(*),
    LOGIN_COUNT NUMBER(*)
);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (1, '程柯', 'admin', 'admin', null, null, null, null, null, null, null);