create table ZG_USER_ROLE
(
    USER_ID NUMBER not null,
    ROLE_ID NUMBER not null,
    constraint USER_ROLE_PK
        primary key (USER_ID, ROLE_ID)
)
/

INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (4, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (5, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (6, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (7, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (8, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (9, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (10, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (11, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (12, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (13, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (14, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (15, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (16, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (17, 2);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (18, 2);