create table ZG_USER
(
    ID            NUMBER                    not null,
    CNNAME        VARCHAR2(50),
    USERNAME      VARCHAR2(50) default NULL not null
        primary key,
    PASSWORD      VARCHAR2(50),
    EMAIL         VARCHAR2(50),
    TELEPHONE     VARCHAR2(50),
    MOBILE_PHONE  VARCHAR2(50),
    WECHAT_ID     VARCHAR2(50),
    SKILL         VARCHAR2(50),
    DEPARTMENT_ID VARCHAR2(50) default NULL,
    LOGIN_COUNT   NUMBER
)
/

INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (3, '刘志鹏', 'liuzp', '76f2ceb5ac69f186790789cb8ca11bae', null, '12345678', '123', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (4, '杨波', 'yangb', 'cf34a90812c11acf217dc0eddfc53def', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (1, 'admin', 'admin', '04bd781e9868f4ebbd5dab73551612fa', 'chengk@bocd.com.cn', '86160897', '15008426617', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (5, '罗新', 'luoxin', '60a36ad5f598736166379991cfbd0a99', null, '911111', '9111111', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (6, 'admin2', 'admin2', '6a9118b2427044df0194a1e5f0cf63d1', null, '55555', '555555', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (7, '谢飞', 'xiefei', '1fcfb0b4ac08c68e7d4e5e9af6f2636e', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (8, '欧少', 'ousy', '598f6322353cbc2aad82c5bf6e392796', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (2, '何杰', 'hejie', 'a1b680583ccd9532d7947a1847bcf2f0', null, '555', '555', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (9, 'admin3', 'admin3', '6cda43077dbc9cf1ac2359c03d9400cb', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (10, 'admin4', 'admin4', 'a967fd8a90f87e0353e6c6a71a6683e3', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (11, '杨林', 'yanglin', '427a16779aeb5af535caf54fc1a40d76', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (12, 'admin5hmp', 'admin5', '786fbf670c53f37a12080404dd5132af', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (13, 'admin6', 'admin6', 'cec47e5947d96ef201ff661184e64933', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (14, 'admin7', 'admin7', 'd16d89a93c7136fd633871660d39f306', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (15, 'admin8', 'admin8', 'b38e53ffefa71a61404396e645fdc80b', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (16, 'admin9', 'admin9', 'f5cf1adf351bc72ff367b5193b50bf51', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (17, 'admin10', 'admin10', '7e9d207f925c9bdcb6ee5eee5c7b1c8d', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (18, 'admin11', 'admin11', 'bb4fa8b74fec20a7a2cfc982bc04a353', null, null, null, null, null, null, null);