CREATE TABLE ZG.ZG_USER_ROLE
(
    USER_ID NUMBER(*) NOT NULL,
    ROLE_ID NUMBER(*) NOT NULL,
    CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID)
);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (3, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (4, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (5, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (6, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (7, 1);
INSERT INTO ZG.ZG_USER_ROLE (USER_ID, ROLE_ID) VALUES (8, 1);