CREATE TABLE ZG.ZG_USER_DEP
(
    USER_ID NUMBER(*) NOT NULL,
    DEP_ID NUMBER(*) DEFAULT NULL NOT NULL,
    CONSTRAINT ZG_USER_DEP_USER_ID_DEP_ID_PK PRIMARY KEY (USER_ID, DEP_ID)
);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (1, 9999);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (2, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (3, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (4, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (5, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (6, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (7, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (8, 101);