CREATE TABLE ZG.ZG_USER
(
    ID NUMBER(*) NOT NULL,
    CNNAME VARCHAR2(50),
    USERNAME VARCHAR2(50) DEFAULT NULL NOT NULL,
    PASSWORD VARCHAR2(50),
    EMAIL VARCHAR2(50),
    TELEPHONE VARCHAR2(50),
    MOBILE_PHONE VARCHAR2(50),
    WECHAT_ID VARCHAR2(50),
    SKILL VARCHAR2(50),
    DEPARTMENT_ID VARCHAR2(50) DEFAULT NULL,
    LOGIN_COUNT NUMBER(*)
);
CREATE UNIQUE INDEX ZG_USER_USERNAME_UINDEX ON ZG.ZG_USER (USERNAME);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (3, '刘志鹏', 'liuzp', '76f2ceb5ac69f186790789cb8ca11bae', null, '123', '123', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (4, '杨波', 'yangb', 'cf34a90812c11acf217dc0eddfc53def', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (1, '程大柯xx', 'admin', '04bd781e9868f4ebbd5dab73551612fa', 'chengk@bocd.com.cn', '123', '123', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (5, '罗新', 'luoxin', '60a36ad5f598736166379991cfbd0a99', null, '911111', '9111111', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (6, 'admin2', 'admin2', '6a9118b2427044df0194a1e5f0cf63d1', null, '55555', '555555', null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (7, '谢飞', 'xiefei', '1fcfb0b4ac08c68e7d4e5e9af6f2636e', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (8, '欧少', 'ousy', '598f6322353cbc2aad82c5bf6e392796', null, null, null, null, null, null, null);
INSERT INTO ZG.ZG_USER (ID, CNNAME, USERNAME, PASSWORD, EMAIL, TELEPHONE, MOBILE_PHONE, WECHAT_ID, SKILL, DEPARTMENT_ID, LOGIN_COUNT) VALUES (2, '何杰', 'hejie', 'a1b680583ccd9532d7947a1847bcf2f0', null, '555', '555', null, null, null, null);