CREATE TABLE ZG.ZG_USER_DEP
(
    USER_ID NUMBER(*) NOT NULL,
    DEP_ID NUMBER(*) DEFAULT NULL NOT NULL,
    CONSTRAINT ZG_USER_DEP_USER_ID_DEP_ID_PK PRIMARY KEY (USER_ID, DEP_ID)
);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (1, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (2, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (3, 9999);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (4, 9999);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (5, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (6, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (7, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (8, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (9, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (10, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (11, 9999);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (12, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (13, 9999);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (14, 9999);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (15, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (16, 101);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (17, 9999);
INSERT INTO ZG.ZG_USER_DEP (USER_ID, DEP_ID) VALUES (18, 9999);